export const ItemData = [
  { "id": 1, "name": "Tropical Beach", "imageUrl": "https://wallpaperaccess.com/full/424849.jpg", "price": 250.00 },
  { "id": 2, "name": "Mountain Adventure", "imageUrl": "https://example.com/images/mountain-adventure.jpg", "price": 200.00 },
  { "id": 3, "name": "City Escape", "imageUrl": "https://example.com/images/city-escape.jpg", "price": 120.00 },
  { "id": 4, "name": "Desert Safari", "imageUrl": "https://example.com/images/desert-safari.jpg", "price": 180.00 },
  { "id": 5, "name": "Forest Retreat", "imageUrl": "https://example.com/images/forest-retreat.jpg", "price": 160.00 },
  { "id": 6, "name": "Island Getaway", "imageUrl": "https://example.com/images/island-getaway.jpg", "price": 250.00 },
  { "id": 7, "name": "Cultural Tour", "imageUrl": "https://example.com/images/cultural-tour.jpg", "price": 130.00 },
  { "id": 8, "name": "Cruise Adventure", "imageUrl": "https://example.com/images/cruise-adventure.jpg", "price": 300.00 },
  { "id": 9, "name": "Wildlife Expedition", "imageUrl": "https://example.com/images/wildlife-expedition.jpg", "price": 220.00 },
  { "id": 10, "name": "Historical Journey", "imageUrl": "https://example.com/images/historical-journey.jpg", "price": 140.00 },
  { "id": 11, "name": "Snowy Mountains", "imageUrl": "https://example.com/images/snowy-mountains.jpg", "price": 210.00 },
  { "id": 12, "name": "Serene Lake", "imageUrl": "https://example.com/images/serene-lake.jpg", "price": 170.00 },
  { "id": 13, "name": "Vibrant City", "imageUrl": "https://example.com/images/vibrant-city.jpg", "price": 140.00 },
  { "id": 14, "name": "Lush Green Hills", "imageUrl": "https://example.com/images/lush-green-hills.jpg", "price": 165.00 },
  { "id": 15, "name": "Ancient Ruins", "imageUrl": "https://example.com/images/ancient-ruins.jpg", "price": 180.00 },
  { "id": 16, "name": "Beach Sunset", "imageUrl": "https://example.com/images/beach-sunset.jpg", "price": 155.00 },
  { "id": 17, "name": "Countryside Escape", "imageUrl": "https://example.com/images/countryside-escape.jpg", "price": 140.00 },
  { "id": 18, "name": "Island Paradise", "imageUrl": "https://example.com/images/island-paradise.jpg", "price": 300.00 },
  { "id": 19, "name": "Adventure Sports", "imageUrl": "https://example.com/images/adventure-sports.jpg", "price": 210.00 },
  { "id": 20, "name": "Canyon Exploration", "imageUrl": "https://example.com/images/canyon-exploration.jpg", "price": 220.00 },
  { "id": 21, "name": "Gorgeous Waterfalls", "imageUrl": "https://example.com/images/gorgeous-waterfalls.jpg", "price": 175.00 },
  { "id": 22, "name": "Cultural Heritage", "imageUrl": "https://example.com/images/cultural-heritage.jpg", "price": 130.00 },
  { "id": 23, "name": "Mediterranean Coast", "imageUrl": "https://example.com/images/mediterranean-coast.jpg", "price": 240.00 },
  { "id": 24, "name": "Sunny Vineyard", "imageUrl": "https://example.com/images/sunny-vineyard.jpg", "price": 180.00 },
  { "id": 25, "name": "Coastal Cliffs", "imageUrl": "https://example.com/images/coastal-cliffs.jpg", "price": 190.00 },
  { "id": 26, "name": "Enchanting Forest", "imageUrl": "https://example.com/images/enchanting-forest.jpg", "price": 160.00 },
  { "id": 27, "name": "Starlit Desert", "imageUrl": "https://example.com/images/starlit-desert.jpg", "price": 200.00 },
  { "id": 28, "name": "Charming Village", "imageUrl": "https://example.com/images/charming-village.jpg", "price": 145.00 },
  { "id": 29, "name": "Artistic Cityscape", "imageUrl": "https://example.com/images/artistic-cityscape.jpg", "price": 175.00 },
  { "id": 30, "name": "River Cruise", "imageUrl": "https://example.com/images/river-cruise.jpg", "price": 210.00 },
  { "id": 31, "name": "Trekking Trails", "imageUrl": "https://example.com/images/trekking-trails.jpg", "price": 190.00 },
  { "id": 32, "name": "Island Hopping", "imageUrl": "https://example.com/images/island-hopping.jpg", "price": 250.00 },
  { "id": 33, "name": "Relaxing Spa", "imageUrl": "https://example.com/images/relaxing-spa.jpg", "price": 220.00 },
  { "id": 34, "name": "Scenic Railway", "imageUrl": "https://example.com/images/scenic-railway.jpg", "price": 160.00 },
  { "id": 35, "name": "Luxury Resort", "imageUrl": "https://example.com/images/luxury-resort.jpg", "price": 350.00 },
  { "id": 36, "name": "Beautiful Countryside", "imageUrl": "https://example.com/images/beautiful-countryside.jpg", "price": 145.00 },
  { "id": 37, "name": "Picturesque Lake", "imageUrl": "https://example.com/images/picturesque-lake.jpg", "price": 175.00 },
  { "id": 38, "name": "Exciting Wildlife Safari", "imageUrl": "https://example.com/images/exciting-wildlife-safari.jpg", "price": 270.00 },
  { "id": 39, "name": "Charming Bungalows", "imageUrl": "https://example.com/images/charming-bungalows.jpg", "price": 160.00 },
  { "id": 40, "name": "Festive Celebration", "imageUrl": "https://example.com/images/festive-celebration.jpg", "price": 130.00 }
    
  ]